### ISSUE TITLE
qt.inline build fails

### ISSUE THREAD

**Issue by lamg** [kitech/qt.go#7]
`make` step fails in OpenSUSE Leap 42.3 with:
```
qt.inline/src/core/qbasicmutex.cxx:53:39: error: no member named 'try_lock' in 'QBasicMutex';
      did you mean 'tryLock'?
  return (bool)((QBasicMutex*)this_)->try_lock();
                                      ^~~~~~~~
                                      tryLock
/usr/include/qt5/QtCore/qmutex.h:68:10: note: 'tryLock' declared here
    bool tryLock() Q_DECL_NOTHROW {
         ^
1 error generated.
```

**Comment by kitech** [comment]
need qt 5.10, see requirement, https://github.com/kitech/qt.inline/blob/master/readme.md

**Comment by kitech** [comment]
prebuild version here: https://github.com/kitech/qt.inline/releases/tag/v1.0-rc.1

**Comment by kitech** [comment]
what's your system qt version? need qt5.10

**Comment by pebbe** [comment]
Debian stable has qt version 5.7, unstable and testing have 5.9. Old stable has 5.3

Ubuntu 16 LTS has 5.5, Ubuntu 17 has 5.9, the next version of Ubuntu will also have 5.9. Old LTS has 5.2.

If you want your package to work for many people, you should make it work with qt version 5.2

**Comment by kitech** [comment]
for simple, add static build for test, https://github.com/kitech/qt.inline/releases/download/v1.0-rc.1/qt510_linux_x64_static.tar.gz
